// ═══════════════════════════════════════════════
// FSM (Finite State Machine) Types
// ═══════════════════════════════════════════════

export enum CallState {
  GREETING = 'GREETING',
  PATIENT_TYPE_DETECT = 'PATIENT_TYPE_DETECT',
  FAQ_ANSWERING = 'FAQ_ANSWERING',
  RETURNING_PATIENT_LOOKUP = 'RETURNING_PATIENT_LOOKUP',
  NEW_PATIENT_PHONE_CONFIRM = 'NEW_PATIENT_PHONE_CONFIRM',
  SEND_FORM_LINK = 'SEND_FORM_LINK',
  WAITING_FOR_FORM = 'WAITING_FOR_FORM',
  VERBAL_COLLECTION = 'VERBAL_COLLECTION',
  FORM_RECEIVED = 'FORM_RECEIVED',
  CHIEF_COMPLAINT = 'CHIEF_COMPLAINT',
  APPOINTMENT_SEARCH = 'APPOINTMENT_SEARCH',
  PRESENT_OPTIONS = 'PRESENT_OPTIONS',
  CONFIRM_BOOKING = 'CONFIRM_BOOKING',
  CLOSING = 'CLOSING',
  ERROR_RECOVERY = 'ERROR_RECOVERY'
}
